export const ALL_CARS = [
    {
        id: '1',
        name: 'Tesla Model S Plaid',
        category: 'Electric Sport',
        price: 189,
        image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?q=80&w=2670&auto=format&fit=crop',
        features: { passengers: 5, fuel: 'Electric', transmission: 'Auto' },
        available: true,
    },
    {
        id: '2',
        name: 'Porsche 911 GT3',
        category: 'Supercar',
        price: 350,
        image: 'https://images.unsplash.com/photo-1503376763036-066120622c74?q=80&w=2670&auto=format&fit=crop',
        features: { passengers: 2, fuel: 'Petrol', transmission: 'Auto' },
        available: false,
    },
    {
        id: '3',
        name: 'Range Rover SV',
        category: 'Luxury SUV',
        price: 250,
        image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?q=80&w=2670&auto=format&fit=crop',
        features: { passengers: 5, fuel: 'Hybrid', transmission: 'Auto' },
        available: true,
    },
    {
        id: '4',
        name: 'Mercedes-AMG G63',
        category: 'Luxury SUV',
        price: 320,
        image: 'https://images.unsplash.com/photo-1520031441872-265e4ff70366?q=80&w=2670&auto=format&fit=crop',
        features: { passengers: 5, fuel: 'Petrol', transmission: 'Auto' },
        available: true,
    },
    {
        id: '5',
        name: 'Audi RS e-tron GT',
        category: 'Electric Sport',
        price: 220,
        image: 'https://images.unsplash.com/photo-1614200187524-dc411b872b6c?q=80&w=2670&auto=format&fit=crop',
        features: { passengers: 4, fuel: 'Electric', transmission: 'Auto' },
        available: true,
    },
    {
        id: '6',
        name: 'Ferrari 488 Spider',
        category: 'Supercar',
        price: 450,
        image: 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?q=80&w=2670&auto=format&fit=crop',
        features: { passengers: 2, fuel: 'Petrol', transmission: 'Auto' },
        available: false,
    },
];
